raleigh_analytics:
  outputs:
    dev:
      type: duckdb
      path: /workspaces/raleigh_greenway_safety/raleigh_greenway.duckdb
      extensions:
        - spatial
      settings:
        external_access: true
  target: dev