name: 'raleigh_analytics'
version: '1.0.0'
profile: 'raleigh_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  raleigh_analytics:
      +materialized: view